# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ease', models.DecimalField(decimal_places=10, max_digits=19)),
                ('fonts_color', models.DecimalField(decimal_places=10, max_digits=19)),
                ('simple_design', models.DecimalField(decimal_places=10, max_digits=19)),
                ('animations', models.DecimalField(decimal_places=10, max_digits=19)),
                ('table', models.DecimalField(decimal_places=10, max_digits=19)),
                ('lists', models.DecimalField(decimal_places=10, max_digits=19)),
                ('forms', models.DecimalField(decimal_places=10, max_digits=19)),
                ('variables_data', models.DecimalField(decimal_places=10, max_digits=19)),
                ('json', models.DecimalField(decimal_places=10, max_digits=19)),
                ('flexbox', models.DecimalField(decimal_places=10, max_digits=19)),
                ('do_anchors', models.DecimalField(decimal_places=10, max_digits=19)),
                ('structure', models.DecimalField(decimal_places=10, max_digits=19)),
                ('moves', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.Category'),
            preserve_default=False,
        ),
    ]
